### ISSUE TITLE
Ошибка "Недопустимые данные"

### ISSUE THREAD

**Issue by nm17** [ingenerkateam/color-game#1]
```
#1: TXLib [Ver: 00172a, Rev: 104], 
Instance: 0x00E25954,
Flags: CmdreT,
Thread: 0x00002690 (Main),
GetLastError(): 13 (Недопустимые данные).
From: c:\users\адм\documents\agit\color-game\txlib.h (5687) 
bool __cdecl `anonymous-namespace'::TX::_txCanvas_OK(void).
```

**Comment by mabramovsd** [comment]
Код, который вызывает txCanvas_OK, можно увидеть? Словосочетание "недопустимые данные" вполне может значить, что txCanvas_OK нужны входные данные (вместо void). А может окно рисования не создано. Без кода фиг поймешь в общем

**Comment by mabramovsd** [comment]
Судя по https://github.com/ingenerkateam/color-game/blob/master/TXLib.h#L5685 скорее всего ты вызываешь txOK до создания окна (т.е. до вызова txCreateWindow)

**Comment by nm17** [comment]
@mabramovsd, Единственное что я делаю до txCreateWindow() это читаю int переменную

**Comment by nm17** [comment]
При переходе на df556b6 тоже самое.
